/*************************************************
Initially Generated by SSoT.me - 2017
    EJ Alexandra - An odxml42 Tool
    This file will not be overwritten by default!
*************************************************/
using System;
using System.Collections.Generic;
using System.ComponentModel;
using MorseCodeHelper.Lib.SqlDataManagement;

namespace MorseCodeHelper.Lib.DataClasses
{                   
    
    public partial class Alphabet 
    {
        public Alphabet()
        {
            this.InitPoco();
        }

        public override String ToString()
        {
            return String.Format("Alphabet: {0}", this.Name);
        }

        internal void ParseCharacters(SqlDataManager sdm, List<Signal> allSignals)
        {
            var charSequenceWhere = String.Format("CharacterId IN (SELECT CharacterId from Character where AlphabetId = '{0}')", this.AlphabetId);
            var charSequences = sdm.GetAllCharacterSquences<CharacterSquence>(charSequenceWhere);
            
            foreach (var charToCheck in this.Characters) {
                charToCheck.LoadCharacterSquences(charSequences);
                charToCheck.ParseSequence(sdm, allSignals);
            }
        }
    }
}