/*************************************************
Initially Generated by SSoT.me - 2017
    EJ Alexandra - An odxml42 Tool
    This file will not be overwritten by default!
*************************************************/
using System;
using System.Collections.Generic;
using System.ComponentModel;
using MorseCodeHelper.Lib.SqlDataManagement;
using System.Linq;

namespace MorseCodeHelper.Lib.DataClasses
{                   
    
    public partial class Character 
    {
        public Character()
        {
            this.InitPoco();
        }

        public override String ToString()
        {
            return String.Format("Character: {0}", this.Name);
        }

        internal void ParseSequence(SqlDataManager sdm, List<Signal> allSignals)
        {
            var signalDict = allSignals.ToDictionary(signal => signal.Symbol);
            this.DeleteSequence(sdm);
            foreach (var sequenceChar in this.SequenceCode) {
                var cs = new CharacterSquence()
                {
                    Name = sequenceChar.ToString(),
                    Description = signalDict[sequenceChar.ToString()].Name,
                    CharacterId = this.CharacterId,
                    SignalId = signalDict[sequenceChar.ToString()].SignalId,
                    SignalIndex = this.CharacterSquences.Count() + 1
                };
                this.CharacterSquences.Add(cs);
                sdm.Insert(cs);
            }
        }

        private void DeleteSequence(SqlDataManager sdm)
        {
            foreach (var charSequence in this.CharacterSquences) sdm.Delete(charSequence);
            this.CharacterSquences.Clear();
        }
    }
}