/*************************************************
Initially Generated by SSoT.me - 2017
    EJ Alexandra - An odxml42 Tool
    This file will not be overwritten by default!
*************************************************/
using MorseCodeHelper.Lib.SqlDataManagement;
using System;
using System.ComponentModel;
using System.Collections.Generic;
using System.Linq;

namespace MorseCodeHelper.Lib.DataClasses
{

    public partial class Signal
    {
        public static List<Signal> AllSignals { get; }
        public static Dictionary<Guid, Signal> SignalsById { get; }

        public Signal()
        {
            this.InitPoco();
        }

        static Signal()
        {
            var sdm = new SqlDataManager();
            Signal.AllSignals = sdm.GetAllSignals<Signal>();
            Signal.SignalsById = AllSignals.ToDictionary(signal => signal.SignalId);
        }

        public override String ToString()
        {
            return String.Format("Signal: {0}", this.Name);
        }

        internal static void Play(Guid signalId)
        {
            var signal = SignalsById[signalId];
            signal.Play();
        }

        private void Play()
        {
            Console.WriteLine("SIGNAL: {0}", this.Name);
        }
    }
}